trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: call build-xiph.bat
  displayName: 'bootstrap and build vcpkg and xiph libraries'
- script: call pack-xiph.bat
  displayName: 'package xiph libraries as NuGet package'
