# Starter pipeline


trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

pool:
  vmImage: 'vs2017-win2016'

- task: CmdLine@2
  displayName: 'bootstrap and build vcpkg'
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
