# Starter pipeline


trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

pool:
  vmImage: 'vs2017-win2016'

- script: build-xiph.bat
  displayName: 'bootstrap and build vcpkg and xiph libraries'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
